name: MSRV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MSRV_TOOLCHAIN: '1.81.0'

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust (${{ env.MSRV_TOOLCHAIN }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MSRV_TOOLCHAIN }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ env.MSRV_TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build (all features) on MSRV
        run: cargo build --all-features
