name: Publish (dry-run)

on:
  workflow_dispatch:
  push:
    tags:
      - 'oxidizr-arch-v*.*.*'

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Verify package metadata
        run: cargo package --allow-dirty --verbose
      - name: Publish dry run
        run: cargo publish --dry-run --allow-dirty --verbose
      # To perform a real publish, add CRATES_IO_TOKEN in repo secrets and uncomment:
      # - name: Publish
      #   if: startsWith(github.ref, 'refs/tags/oxidizr-arch-v')
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      #   run: cargo publish --verbose
